### ISSUE TITLE
how to use in a directive

### ISSUE THREAD

**Issue by armyofda12mnkeys** [bendrucker/angular-ziptastic#3]
I'm kinda new to angular and was curious how to use your module (im evaluating Ziptastic in angular and if it works out I'll purchase Ziptastic to make more API requests [guessing there's a way to pass your api-key or something like that via your plugin to prove you are the purchaser of the API?]).

Here is a jsfiddle that Im trying to simple popup the city/state based on the zip code:
http://jsfiddle.net/armyofda12mnkeys/Leym2zaz/2/

**Comment by bendrucker** [comment]
Wasn't aware that there were paid plans now. Unless an API provides a means to restrict the hosts from which requests can originate, you really can't use it client side. 

You could certainly build a directive that would debounce updates and write to a specified model. Dealing with something like that isn't really related to this service and is more than I can volunteer to help with via Issues.

**Comment by armyofda12mnkeys** [comment]
Just a quick followup:

I got the directive working with a friend, having a directive write to a model like you suggested, if anyone else is interested:
http://jsfiddle.net/armyofda12mnkeys/2nrcwukz/8/

> Unless an API provides a means to restrict the hosts from which requests can originate, you really can't use it client side.

Well _I assume_ they restrict hosts based on # of requests coming in per day. I wonder if when you purchase more requests per day, if they ask you to enter a domain to use ziptastic on (would kinda stink since I am trying to use it in angular-clients that may be distributed to different websites). Anyway I guess thats a question for them.

**Comment by bendrucker** [comment]
The directive you wrote there knows exactly what its parent scope looks like. There's really no point in stuffing functionality inside a directive if it's going to know exactly how the controller and all your business logic works. At that point just do the watching and updates from your controller. 

Services that have client access can work one of two ways:
1. The client holds a public key that's useless without a private key that's on your server (e.g. Stripe.js)
2. Requests must come from a predefined set of domains (e.g. Sentry)

That's it, no other way to do it. Otherwise anyone could just grab your key and start using your quota for their own app.
